// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFttOHS_NTy-9UC-NuP1r-gJj2BbPjPNA',
    appId: '1:337376899602:web:5333cb0ff3fb93783c9ecb',
    messagingSenderId: '337376899602',
    projectId: 'ibarber-demo-alpha',
    authDomain: 'ibarber-demo-alpha.firebaseapp.com',
    storageBucket: 'ibarber-demo-alpha.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYwQRRrN5cVJ-x634cDj8xZZPVucs_wcU',
    appId: '1:337376899602:android:8adb56140bce83193c9ecb',
    messagingSenderId: '337376899602',
    projectId: 'ibarber-demo-alpha',
    storageBucket: 'ibarber-demo-alpha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmRrVb1EpXHl_pAvQye8jBFQJi6TlrDG0',
    appId: '1:337376899602:ios:01b36345790be3703c9ecb',
    messagingSenderId: '337376899602',
    projectId: 'ibarber-demo-alpha',
    storageBucket: 'ibarber-demo-alpha.appspot.com',
    iosClientId: '337376899602-5s6t6rcj9are94f6i7rf8chdetrr7o3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmRrVb1EpXHl_pAvQye8jBFQJi6TlrDG0',
    appId: '1:337376899602:ios:921bd01e5bbcdc233c9ecb',
    messagingSenderId: '337376899602',
    projectId: 'ibarber-demo-alpha',
    storageBucket: 'ibarber-demo-alpha.appspot.com',
    iosClientId: '337376899602-13s1do93i1tb101043ekguivkj0o5mac.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
